services:
  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  pg_data: