# Generated by Django 5.1.2 on 2025-05-21 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishbattle', '0002_practicerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('explanation', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishbattle.answer')),
            ],
        ),
    ]
