# Generated by Django 5.1.2 on 2025-05-13 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
